spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/User/**  # Matches /User context path
          filters:
            - RewritePath=/User/(?<segment>.*), /${segment}  # Removes /User

        - id: profile-service
          uri: http://localhost:8082
          predicates:
            - Path=/Profile/**  # Matches /Profile context path
          filters:
            - RewritePath=/Profile/(?<segment>.*), /${segment}  # Removes /Profile

        - id: list-service
          uri: http://localhost:8083
          predicates:
            - Path=/ListService/**  # Matches /ListService context path
          filters:
            - RewritePath=/ListService/(?<segment>.*), /${segment}  # Removes /ListService

        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/Order/**  # Matches /Order context path
          filters:
            - RewritePath=/Order/(?<segment>.*), /${segment}  # Removes /Order

        - id: payment-service
          uri: http://localhost:8085
          predicates:
            - Path=/Payment/**  # Matches /Payment context path
          filters:
            - RewritePath=/Payment/(?<segment>.*), /${segment}  # Removes /Payment

  main:
    web-application-type: reactive
