spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /${segment}
        - id: profile-service
          uri: http://localhost:8082
          predicates:
            - Path=/profiles/**
          filters:
            - RewritePath=/profiles/(?<segment>.*), /${segment}
        - id: service3
          uri: http://localhost:8083
          predicates:
            - Path=/service3/**
          filters:
            - RewritePath=/service3/(?<segment>.*), /${segment}
        - id: service4
          uri: http://localhost:8084
          predicates:
            - Path=/service4/**
          filters:
            - RewritePath=/service4/(?<segment>.*), /${segment}
        - id: service5
          uri: http://localhost:8085
          predicates:
            - Path=/service5/**
          filters:
            - RewritePath=/service5/(?<segment>.*), /${segment}
